### ISSUE TITLE
Can't load multiple entity directories in Weltmeister

### ISSUE THREAD

**Issue by jessefreeman** [namuol/node-impact-weltmeister#1]
While running the server.js to replace the need for the glob.php file I noticed that configuring Weltmeister to load entities from more than one directory silently fails. Example, in the config.js for Weltmeister you should be able to do something like this:

```
'entityFiles': ['lib/game/entities/*.js',
                'lib/bootstrap/entities/*.js'],
```

but if you load Weltmeister no entities show up and if I log the success I don't see any files opened. Impact will generate the following URL:

```
path lib/weltmeister/api/glob.php?glob[]=lib%2Fgame%2Fentities%2F*.js&glob[]=lib%2Faction-pack%2Fentities%2F*.js&nocache=0.9554271688684821
```

but it doesn't appear to be valid to the glob.js script.

**Comment by namuol** [comment]
Looks like it might be broken entirely; are you using Impact 1.22?

**Comment by jessefreeman** [comment]
Yes, I'm using the latest version of impact. Didn't try it with an older version. Do you think it's an impact bug?

**Comment by namuol** [comment]
Nah, it's just some code rot, I'm afraid. There must have been a subtle API change in the PHP backend. I think it used to expect a leading `/` but no longer does.

But yeah, multiple entries wouldn't have worked with previous versions either. Fix on the way. :)

**Comment by namuol** [comment]
Give it a try now; there might be some other things broken that I haven't tested yet. Thanks for the report!
